global.testData = {
    BANKADMIN_CREATEROLE : {},
    CREATE_TO_REJECT_ROLES: {},
    SUPERADMIN_CREATED_ROLES:{},
    SUPERADMIN_CREATE_TO_REJECT: {}, 
    CREATE_CORPORATE_USER_ROLE: {},
    CREATE_CORPORATE_REJECT_ROLE: {},
    CORPORATE_ADMIN_USER : {},
    CREATED_USERS:{}, 
    REJECT_USERS: {},
    CONNECTOR_NAME: {}
}